# Generated by Django 3.2.2 on 2021-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='юзер айди')),
                ('name', models.CharField(max_length=255, verbose_name='имя героя')),
                ('gender', models.BooleanField(verbose_name='')),
                ('apples', models.IntegerField(verbose_name='яблоки')),
                ('moneys', models.IntegerField(verbose_name='деньги')),
                ('health', models.IntegerField(verbose_name='здоровье')),
                ('level', models.IntegerField(verbose_name='уровень')),
                ('inventory', models.TextField(verbose_name='инвентарь')),
                ('weapon', models.CharField(max_length=255, verbose_name='оружие')),
            ],
            options={
                'verbose_name': 'герой',
                'verbose_name_plural': 'герои',
                'db_table': 'users',
                'ordering': ['user_id'],
            },
        ),
    ]
